import{initDB,all,add,remove,questionsFor,deleteBankCascade,backup,restore}from'./database.js';import{shuffle,normalizeAnswers}from'./exam.js';
const $=s=>document.querySelector(s);let currentBank=null,quiz=null;await initDB();renderBanks();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
async function renderBanks(){const banks=await all('banks');$('#banks').innerHTML=banks.length?'':'<p class="muted">Δεν υπάρχουν ακόμη τράπεζες ερωτήσεων.</p>';for(const b of banks){const qs=await questionsFor(b.id),d=document.createElement('div');d.className='card bank-card';d.innerHTML=`<h3>${esc(b.name)}</h3><p class="muted">${qs.length} ερωτήσεις</p><div class="card-actions"><button class="open-bank">Άνοιγμα</button><button class="danger delete-bank">Διαγραφή</button></div>`;d.querySelector('.open-bank').onclick=()=>openBank(b);d.querySelector('.delete-bank').onclick=async()=>{if(confirm(`Να διαγραφεί η τράπεζα "${b.name}" και όλες οι ερωτήσεις της;`)){await deleteBankCascade(b.id);if(currentBank?.id===b.id)currentBank=null;renderBanks()}};$('#banks').append(d)}}
$('#newBank').onclick=async()=>{const name=prompt('Όνομα τράπεζας ερωτήσεων:');if(name?.trim()){await add('banks',{name:name.trim(),createdAt:Date.now()});renderBanks()}};
async function openBank(b){currentBank=b;$('#home').hidden=true;$('#resultsView').hidden=true;$('#quizView').hidden=true;$('#bankView').hidden=false;$('#bankTitle').textContent=b.name;renderQuestions()}
async function renderQuestions(){const qs=await questionsFor(currentBank.id);$('#questions').innerHTML=qs.length?'':'<p class="muted">Δεν υπάρχουν ερωτήσεις.</p>';qs.forEach((q,i)=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<strong>${i+1}. ${esc(q.text)}</strong><p class="muted">${esc(q.type||'single')} · ${esc(q.category||'')} ${q.difficulty?'· '+esc(q.difficulty):''}<br>Σωστή: ${esc((q.correct||[]).join(', '))}</p>`;$('#questions').append(d)})}
$('#backBtn').onclick=()=>{$('#bankView').hidden=true;$('#home').hidden=false;renderBanks()};
$('#addQuestion').onclick=()=>$('#questionDialog').showModal();$('#questionForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;const opts={A:$('#qA').value,B:$('#qB').value,C:$('#qC').value,D:$('#qD').value};const correct=normalizeAnswers($('#qCorrect').value);await add('questions',{bankId:currentBank.id,type:correct.length>1?'multiple':'single',text:$('#qText').value,options:opts,correct,explanation:$('#qExplanation').value,category:'',difficulty:'',tags:[]});e.target.reset();renderQuestions()});
$('#csvFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;let bankId=null;try{const rows=parseCSV(await f.text());if(rows.length<2)throw new Error('Το CSV δεν περιέχει ερωτήσεις.');const h=rows[0].map(x=>x.replace(/^\uFEFF/,'').trim().toLowerCase());if(!h.includes('question'))throw new Error('Λείπει η στήλη question.');if(!h.includes('correct'))throw new Error('Λείπει η στήλη correct.');let bankName=prompt('Όνομα τράπεζας για το CSV:',f.name.replace(/\.csv$/i,''));if(!bankName)return;bankId=await add('banks',{name:bankName,createdAt:Date.now()});let count=0;for(const r of rows.slice(1)){const o=Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()]));if(!o.question)continue;const correct=normalizeAnswers(o.correct);if(!correct.length)continue;const type=(o.type||(correct.length>1?'multiple':'single')).toLowerCase().replace('-','_');await add('questions',{bankId,type,text:o.question,options:{A:o.a||o.option_a||'',B:o.b||o.option_b||'',C:o.c||o.option_c||'',D:o.d||o.option_d||''},correct,explanation:o.explanation||'',category:o.category||o.domain||'',difficulty:o.difficulty||'',tags:(o.tags||'').split(/[;|]/).map(x=>x.trim()).filter(Boolean),source:o.source||'',source_url:o.source_url||'',verification_status:o.verification_status||''});count++}if(!count)throw new Error('Δεν βρέθηκαν έγκυρες ερωτήσεις.');alert(`Εισήχθησαν ${count} ερωτήσεις.`);renderBanks()}catch(err){if(bankId)await deleteBankCascade(bankId);alert('Αποτυχία εισαγωγής CSV: '+err.message)}finally{e.target.value=''}};
$('#practiceBtn').onclick=()=>startQuiz(true);$('#examBtn').onclick=()=>startQuiz(false);
async function startQuiz(practice){const qs=shuffle(await questionsFor(currentBank.id));if(!qs.length)return alert('Δεν υπάρχουν ερωτήσεις.');quiz={qs,i:0,practice,answers:Array(qs.length).fill(null).map(()=>[]),graded:Array(qs.length).fill(false)};$('#bankView').hidden=true;$('#resultsView').hidden=true;$('#quizView').hidden=false;showQ()}
function showQ(){const q=quiz.qs[quiz.i],chosen=quiz.answers[quiz.i]||[];$('#progress').textContent=`${quiz.i+1}/${quiz.qs.length}`;$('#quizQuestion').textContent=q.text;$('#feedback').textContent='';const box=$('#quizOptions');box.innerHTML='';Object.entries(q.options||{}).filter(([,v])=>v).forEach(([k,v])=>{const b=document.createElement('button');b.className='option';b.dataset.key=k;b.textContent=`${k}. ${v}`;if(chosen.includes(k))b.classList.add('selected');b.onclick=()=>selectAnswer(k,b,q);box.append(b)});if((q.correct||[]).length>1){const s=document.createElement('button');s.textContent=quiz.practice&&quiz.graded[quiz.i]?'Απάντηση υποβλήθηκε':'Υποβολή απαντήσεων';s.className='submit-answer';s.disabled=quiz.practice&&quiz.graded[quiz.i];s.onclick=submitMultiple;box.append(s)}if(quiz.practice&&quiz.graded[quiz.i])showPracticeFeedback(q);$('#prevQuestion').disabled=quiz.i===0;$('#nextQuestion').textContent=quiz.i===quiz.qs.length-1?'Ολοκλήρωση':'Επόμενη →'}
function selectAnswer(k,b,q){if(quiz.practice&&quiz.graded[quiz.i])return;if((q.correct||[]).length>1){const a=new Set(quiz.answers[quiz.i]);a.has(k)?a.delete(k):a.add(k);quiz.answers[quiz.i]=[...a].sort();b.classList.toggle('selected')}else{quiz.answers[quiz.i]=[k];if(quiz.practice){quiz.graded[quiz.i]=true;showQ()}else showQ()}}
function submitMultiple(){if(!(quiz.answers[quiz.i]||[]).length)return alert('Επίλεξε τουλάχιστον μία απάντηση.');if(quiz.practice){quiz.graded[quiz.i]=true;showQ()}}
function isCorrect(i){const a=[...(quiz.answers[i]||[])].sort(),c=[...(quiz.qs[i].correct||[])].sort();return JSON.stringify(a)===JSON.stringify(c)}
function showPracticeFeedback(q){const chosen=quiz.answers[quiz.i]||[],correct=q.correct||[],ok=isCorrect(quiz.i);document.querySelectorAll('#quizOptions .option').forEach(b=>{const k=b.dataset.key;if(correct.includes(k))b.classList.add('correct');else if(chosen.includes(k))b.classList.add('wrong');b.disabled=true});$('#feedback').textContent=(ok?'Σωστά. ':'Λάθος. ')+(q.explanation||`Σωστή: ${correct.join(', ')}`)}
$('#prevQuestion').onclick=()=>{if(quiz.i>0){quiz.i--;showQ()}};
$('#nextQuestion').onclick=()=>{if(quiz.practice&&!quiz.graded[quiz.i]){if(!(quiz.answers[quiz.i]||[]).length)return alert('Απάντησε πρώτα στην ερώτηση.');quiz.graded[quiz.i]=true}if(quiz.i===quiz.qs.length-1)return finishQuiz();quiz.i++;showQ()};
function finishQuiz(){const correct=quiz.qs.reduce((n,_,i)=>n+(isCorrect(i)?1:0),0),answered=quiz.answers.filter(a=>a.length).length,total=quiz.qs.length,wrong=answered-correct,unanswered=total-answered,pct=Math.round(correct*100/total);$('#resultScore').textContent=`${correct} / ${total}`;$('#resultPercent').textContent=`${pct}%`;$('#resultDetails').textContent=`Σωστές: ${correct} · Λάθος: ${wrong} · Αναπάντητες: ${unanswered}`;$('#quizView').hidden=true;$('#resultsView').hidden=false}
$('#resultsBack').onclick=()=>{$('#resultsView').hidden=true;$('#bankView').hidden=false;quiz=null};
$('#quitQuiz').onclick=()=>{if(confirm('Έξοδος από το τεστ; Η τρέχουσα προσπάθεια δεν θα αποθηκευτεί.'))quitQuiz()};function quitQuiz(){$('#quizView').hidden=true;$('#resultsView').hidden=true;$('#bankView').hidden=false;quiz=null}
$('#exportBtn').onclick=async()=>{const blob=new Blob([JSON.stringify(await backup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mtest-local-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(f&&confirm('Θα αντικατασταθούν τα τοπικά δεδομένα. Συνέχεια;')){await restore(JSON.parse(await f.text()));renderBanks()}e.target.value=''};
function parseCSV(t){let rows=[],row=[],v='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x!==''))rows.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x!==''))rows.push(row);return rows}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
