import{initDB,all,add,questionsFor,backup,restore}from'./database.js';import{shuffle,normalizeAnswers}from'./exam.js';
const $=s=>document.querySelector(s);let currentBank=null,quiz=null;await initDB();renderBanks();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
async function renderBanks(){const banks=await all('banks');$('#banks').innerHTML=banks.length?'':'<p class="muted">Δεν υπάρχουν ακόμη τράπεζες ερωτήσεων.</p>';for(const b of banks){const qs=await questionsFor(b.id),d=document.createElement('div');d.className='card';d.innerHTML=`<h3>${esc(b.name)}</h3><p class="muted">${qs.length} ερωτήσεις</p><button>Άνοιγμα</button>`;d.querySelector('button').onclick=()=>openBank(b);$('#banks').append(d)}}
$('#newBank').onclick=async()=>{const name=prompt('Όνομα τράπεζας ερωτήσεων:');if(name?.trim()){await add('banks',{name:name.trim(),createdAt:Date.now()});renderBanks()}};
async function openBank(b){currentBank=b;$('#home').hidden=true;$('#quizView').hidden=true;$('#bankView').hidden=false;$('#bankTitle').textContent=b.name;renderQuestions()}
async function renderQuestions(){const qs=await questionsFor(currentBank.id);$('#questions').innerHTML=qs.length?'':'<p class="muted">Δεν υπάρχουν ερωτήσεις.</p>';qs.forEach((q,i)=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<strong>${i+1}. ${esc(q.text)}</strong><p class="muted">${esc(q.type||'single')} · ${esc(q.category||'')} ${q.difficulty?'· '+esc(q.difficulty):''}<br>Σωστή: ${esc(q.correct.join(', '))}</p>`;$('#questions').append(d)})}
$('#backBtn').onclick=()=>{$('#bankView').hidden=true;$('#home').hidden=false;renderBanks()};
$('#addQuestion').onclick=()=>$('#questionDialog').showModal();$('#questionForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;const opts={A:$('#qA').value,B:$('#qB').value,C:$('#qC').value,D:$('#qD').value};const correct=normalizeAnswers($('#qCorrect').value);await add('questions',{bankId:currentBank.id,type:correct.length>1?'multiple':'single',text:$('#qText').value,options:opts,correct,explanation:$('#qExplanation').value,category:'',difficulty:'',tags:[]});e.target.reset();renderQuestions()});
$('#csvFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const rows=parseCSV(await f.text());if(rows.length<2)throw new Error('Το CSV δεν περιέχει ερωτήσεις.');const h=rows[0].map(x=>x.replace(/^\uFEFF/,'').trim().toLowerCase());if(!h.includes('question'))throw new Error('Λείπει η στήλη question.');if(!h.includes('correct'))throw new Error('Λείπει η στήλη correct.');let bankName=prompt('Όνομα τράπεζας για το CSV:',f.name.replace(/\.csv$/i,''));if(!bankName)return;const bankId=await add('banks',{name:bankName,createdAt:Date.now()});let count=0;for(const r of rows.slice(1)){const o=Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()]));if(!o.question)continue;const correct=normalizeAnswers(o.correct);if(!correct.length)continue;const type=(o.type|| (correct.length>1?'multiple':'single')).toLowerCase().replace('-','_');await add('questions',{bankId,type,text:o.question,options:{A:o.a||o.option_a||'',B:o.b||o.option_b||'',C:o.c||o.option_c||'',D:o.d||o.option_d||''},correct,explanation:o.explanation||'',category:o.category||o.domain||'',difficulty:o.difficulty||'',tags:(o.tags||'').split(/[;|]/).map(x=>x.trim()).filter(Boolean)});count++}if(!count)throw new Error('Δεν βρέθηκαν έγκυρες ερωτήσεις.');alert(`Εισήχθησαν ${count} ερωτήσεις.`);renderBanks()}catch(err){alert('Αποτυχία εισαγωγής CSV: '+err.message)}finally{e.target.value=''}};
$('#practiceBtn').onclick=()=>startQuiz(true);$('#examBtn').onclick=()=>startQuiz(false);async function startQuiz(practice){const qs=shuffle(await questionsFor(currentBank.id));if(!qs.length)return alert('Δεν υπάρχουν ερωτήσεις.');quiz={qs,i:0,score:0,practice,selected:new Set(),answered:false};$('#bankView').hidden=true;$('#quizView').hidden=false;showQ()}
function showQ(){const q=quiz.qs[quiz.i];quiz.answered=false;quiz.selected=new Set();$('#progress').textContent=`${quiz.i+1}/${quiz.qs.length}`;$('#quizQuestion').textContent=q.text;$('#feedback').textContent='';$('#nextQuestion').hidden=true;const box=$('#quizOptions');box.innerHTML='';Object.entries(q.options).filter(([,v])=>v).forEach(([k,v])=>{const b=document.createElement('button');b.className='option';b.dataset.key=k;b.textContent=`${k}. ${v}`;b.onclick=()=>selectAnswer(k,b,q);box.append(b)});if((q.correct||[]).length>1){const s=document.createElement('button');s.textContent='Υποβολή απαντήσεων';s.className='submit-answer';s.onclick=submitMultiple;box.append(s)}}
function selectAnswer(k,b,q){if(quiz.answered)return;if((q.correct||[]).length>1){quiz.selected.has(k)?quiz.selected.delete(k):quiz.selected.add(k);b.classList.toggle('selected')}else{quiz.selected=new Set([k]);grade()}}
function submitMultiple(){if(!quiz.selected.size)return alert('Επίλεξε τουλάχιστον μία απάντηση.');grade()}
function grade(){if(quiz.answered)return;quiz.answered=true;const q=quiz.qs[quiz.i],chosen=[...quiz.selected].sort(),correct=[...q.correct].sort(),ok=JSON.stringify(chosen)===JSON.stringify(correct);if(ok)quiz.score++;document.querySelectorAll('#quizOptions .option').forEach(b=>{const k=b.dataset.key;if(correct.includes(k))b.classList.add('correct');else if(chosen.includes(k))b.classList.add('wrong');b.disabled=true});const sb=$('#quizOptions .submit-answer');if(sb)sb.disabled=true;$('#feedback').textContent=quiz.practice?(ok?'Σωστά. ':'Λάθος. ')+(q.explanation||`Σωστή: ${correct.join(', ')}`):'Η απάντηση καταχωρήθηκε.';$('#nextQuestion').hidden=false}
$('#nextQuestion').onclick=()=>{if(++quiz.i>=quiz.qs.length){alert(`Αποτέλεσμα: ${quiz.score}/${quiz.qs.length} (${Math.round(100*quiz.score/quiz.qs.length)}%)`);quitQuiz()}else showQ()};$('#quitQuiz').onclick=quitQuiz;function quitQuiz(){$('#quizView').hidden=true;$('#bankView').hidden=false;quiz=null}
$('#exportBtn').onclick=async()=>{const blob=new Blob([JSON.stringify(await backup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mtest-local-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(f&&confirm('Θα αντικατασταθούν τα τοπικά δεδομένα. Συνέχεια;')){await restore(JSON.parse(await f.text()));renderBanks()}e.target.value=''};
function parseCSV(t){let rows=[],row=[],v='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x!==''))rows.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x!==''))rows.push(row);return rows}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
