import{initDB,all,add,put,remove,questionsFor,deleteBankCascade,backup,restore}from'./database.js';import{shuffle,normalizeAnswers}from'./exam.js';
const $=s=>document.querySelector(s);let currentBank=null,quiz=null;await initDB();renderBanks();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
async function renderBanks(){const banks=await all('banks');$('#banks').innerHTML=banks.length?'':'<p class="muted">Δεν υπάρχουν ακόμη τράπεζες ερωτήσεων.</p>';for(const b of banks){const qs=await questionsFor(b.id),d=document.createElement('div');d.className='card bank-card';d.innerHTML=`<h3>${esc(b.name)}</h3><p class="muted">${qs.length} ερωτήσεις</p><div class="card-actions"><button class="open-bank">Άνοιγμα</button><button class="danger delete-bank">Διαγραφή</button></div>`;d.querySelector('.open-bank').onclick=()=>openBank(b);d.querySelector('.delete-bank').onclick=async()=>{if(confirm(`Να διαγραφεί η τράπεζα "${b.name}" και όλες οι ερωτήσεις της;`)){await deleteBankCascade(b.id);if(currentBank?.id===b.id)currentBank=null;renderBanks()}};$('#banks').append(d)}}
$('#newBank').onclick=async()=>{const name=prompt('Όνομα τράπεζας ερωτήσεων:');if(name?.trim()){await add('banks',{name:name.trim(),createdAt:Date.now()});renderBanks()}};
async function openBank(b){currentBank=b;$('#home').hidden=true;$('#resultsView').hidden=true;$('#quizView').hidden=true;$('#bankView').hidden=false;$('#bankTitle').textContent=b.name;renderQuestions()}
async function renderQuestions(){const qs=await questionsFor(currentBank.id);$('#questions').innerHTML=qs.length?'':'<p class="muted">Δεν υπάρχουν ερωτήσεις.</p>';qs.forEach((q,i)=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<strong>${i+1}. ${esc(q.text)}</strong><p class="muted">${esc(q.type||'single')} · ${esc(q.category||'')} ${q.difficulty?'· '+esc(q.difficulty):''}<br>Σωστή: ${esc((q.correct||[]).join(', '))}</p>`;$('#questions').append(d)})}
$('#backBtn').onclick=()=>{$('#bankView').hidden=true;$('#home').hidden=false;renderBanks()};
$('#addQuestion').onclick=()=>$('#questionDialog').showModal();$('#questionForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;const opts={A:$('#qA').value,B:$('#qB').value,C:$('#qC').value,D:$('#qD').value};const correct=normalizeAnswers($('#qCorrect').value);await add('questions',{bankId:currentBank.id,type:correct.length>1?'multiple':'single',text:$('#qText').value,options:opts,correct,explanation:$('#qExplanation').value,category:'',difficulty:'',tags:[]});e.target.reset();renderQuestions()});
$('#csvFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;let bankId=null;try{const parsed=await parseImportFile(f);if(!parsed.questions.length)throw new Error('Δεν βρέθηκαν έγκυρες ερωτήσεις.');let bankName=prompt('Όνομα τράπεζας:',parsed.title||f.name.replace(/\.(csv|xlsx?|xls)$/i,''));if(!bankName)return;bankId=await add('banks',{name:bankName,description:parsed.description||'',duration:parsed.duration||'',sourceFile:f.name,createdAt:Date.now()});let count=0;for(const o of parsed.questions){const correct=normalizeAnswers(o.correct);if(!correct.length)continue;await add('questions',{bankId,type:o.type,text:o.question,options:{A:o.option_a||'',B:o.option_b||'',C:o.option_c||'',D:o.option_d||''},correct,explanation:o.explanation||'',category:o.category||'',difficulty:o.difficulty||'',tags:o.tags||[],source:o.source||'',source_url:o.source_url||'',verification_status:o.verification_status||'',points:Number(o.points)||1});count++}if(!count)throw new Error('Δεν βρέθηκαν ερωτήσεις με έγκυρη απάντηση.');alert(`Εισήχθησαν ${count} ερωτήσεις από ${f.name}.`);renderBanks()}catch(err){if(bankId)await deleteBankCascade(bankId);alert('Αποτυχία εισαγωγής: '+err.message)}finally{e.target.value=''}};
async function parseImportFile(f){const ext=(f.name.split('.').pop()||'').toLowerCase();if(ext==='csv')return parseMTestCSV(await f.text());if(ext==='xls'||ext==='xlsx'){if(!window.XLSX)throw new Error('Η βιβλιοθήκη Excel δεν είναι διαθέσιμη. Άνοιξε την εφαρμογή μία φορά με Internet ώστε να αποθηκευτεί.');const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});return parseExcelTemplate(rows)}throw new Error('Υποστηρίζονται αρχεία CSV, XLS και XLSX.')}
function parseMTestCSV(t){const rows=parseCSV(t);if(rows.length<2)throw new Error('Το CSV δεν περιέχει ερωτήσεις.');const h=rows[0].map(x=>String(x).replace(/^\uFEFF/,'').trim().toLowerCase());if(!h.includes('question')||!h.includes('correct'))throw new Error('Το CSV πρέπει να έχει στήλες question και correct.');const questions=[];for(const r of rows.slice(1)){const o=Object.fromEntries(h.map((k,i)=>[k,String(r[i]??'').trim()]));if(!o.question||!o.correct)continue;const correct=normalizeAnswers(o.correct),type=normalizeType(o.type,correct);questions.push({type,question:o.question,option_a:o.a||o.option_a||'',option_b:o.b||o.option_b||'',option_c:o.c||o.option_c||'',option_d:o.d||o.option_d||'',correct:o.correct,explanation:o.explanation||'',category:o.category||o.domain||'',difficulty:o.difficulty||'',tags:(o.tags||'').split(/[;|]/).map(x=>x.trim()).filter(Boolean),source:o.source||'',source_url:o.source_url||'',verification_status:o.verification_status||'',points:o.points||1})}return{questions}}
function parseExcelTemplate(rows){const norm=v=>String(v??'').replace(/\u00a0/g,' ').trim();let header=-1;for(let i=0;i<Math.min(rows.length,30);i++){const r=rows[i].map(v=>norm(v).toLowerCase());if(r.includes('question')&&r.includes('answer')){header=i;break}}if(header<0)throw new Error('Δεν βρέθηκε η γραμμή Question / Answer στο Excel.');const meta={};for(let i=0;i<header;i++){const k=norm(rows[i]?.[0]).toLowerCase(),v=norm(rows[i]?.[1]);if(k==='title')meta.title=v;if(k==='description')meta.description=v;if(k==='duration')meta.duration=v}const h=rows[header].map(v=>norm(v).toLowerCase());const questions=[];for(const r of rows.slice(header+1)){const o=Object.fromEntries(h.map((k,i)=>[k,norm(r[i])]));if(!o.question||!o.answer)continue;let answer=o.answer.toUpperCase(),type=(o.type||'').toLowerCase(),a=o.option1,b=o.option2,c=o.option3,d=o.option4;if(type==='tf'||type==='true_false'||type==='true/false'){type='true_false';a='True';b='False';c='';d='';answer=['T','TRUE','A'].includes(answer)?'A':['F','FALSE','B'].includes(answer)?'B':answer}else{type=normalizeType(type,normalizeAnswers(answer));answer=mapExcelAnswer(answer)}questions.push({type,question:o.question,option_a:a,option_b:b,option_c:c,option_d:d,correct:answer,explanation:o.explanation||'',points:o.points||1,tags:[]})}return{...meta,questions}}
function mapExcelAnswer(v){const x=String(v).toUpperCase().trim();const map={1:'A',2:'B',3:'C',4:'D'};if(map[x])return map[x];return x.replace(/OPTION\s*/g,'').replace(/[;,]+/g,'|')}
function normalizeType(t,correct=[]){t=String(t||'').toLowerCase().replace(/[- ]/g,'_');if(t==='tf'||t==='truefalse'||t==='true/false')return'true_false';if(t==='multiple'||t==='multi'||correct.length>1)return'multiple';return'single'};
$('#practiceBtn').onclick=()=>startQuiz(true);$('#examBtn').onclick=()=>startQuiz(false);
async function startQuiz(practice){
  const allQs=await questionsFor(currentBank.id);if(!allQs.length)return alert('Δεν υπάρχουν ερωτήσεις.');
  if(practice){
    const saved=await getPracticeProgress(currentBank.id);
    if(saved&&saved.questionIds?.length){
      const map=new Map(allQs.map(q=>[q.id,q])),restored=saved.questionIds.map(id=>map.get(id)).filter(Boolean);
      if(restored.length){
        const resume=confirm(`Υπάρχει αποθηκευμένο Practice στην ερώτηση ${Math.min((saved.i||0)+1,restored.length)}/${restored.length}.\n\nOK = Συνέχεια\nCancel = Νέο Practice`);
        if(resume){quiz={qs:restored,i:Math.min(saved.i||0,restored.length-1),practice:true,answers:restored.map((_,i)=>saved.answers?.[i]||[]),graded:restored.map((_,i)=>!!saved.graded?.[i])};return openQuiz()}
      }
    }
  }
  const qs=shuffle(allQs);quiz={qs,i:0,practice,answers:Array(qs.length).fill(null).map(()=>[]),graded:Array(qs.length).fill(false)};if(practice)await savePracticeProgress();openQuiz()
}
function openQuiz(){$('#bankView').hidden=true;$('#resultsView').hidden=true;$('#quizView').hidden=false;showQ()}
async function getPracticeProgress(bankId){return (await all('attempts')).filter(a=>a.bankId===bankId&&a.mode==='practice'&&a.status==='in_progress').sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0]||null}
async function savePracticeProgress(){if(!quiz?.practice||!currentBank)return;let saved=await getPracticeProgress(currentBank.id);const data={id:saved?.id,bankId:currentBank.id,mode:'practice',status:'in_progress',questionIds:quiz.qs.map(q=>q.id),i:quiz.i,answers:quiz.answers,graded:quiz.graded,updatedAt:Date.now(),createdAt:saved?.createdAt||Date.now()};if(data.id)await put('attempts',data);else await add('attempts',data)}
async function clearPracticeProgress(){if(!currentBank)return;for(const a of await all('attempts'))if(a.bankId===currentBank.id&&a.mode==='practice'&&a.status==='in_progress')await remove('attempts',a.id)}
function showQ(){const q=quiz.qs[quiz.i],chosen=quiz.answers[quiz.i]||[];$('#progress').textContent=`${quiz.i+1}/${quiz.qs.length}`;$('#quizQuestion').textContent=q.text;$('#feedback').textContent='';const box=$('#quizOptions');box.innerHTML='';Object.entries(q.options||{}).filter(([,v])=>v).forEach(([k,v])=>{const b=document.createElement('button');b.className='option';b.dataset.key=k;b.textContent=`${k}. ${v}`;if(chosen.includes(k))b.classList.add('selected');b.onclick=()=>selectAnswer(k,b,q);box.append(b)});if((q.correct||[]).length>1){const s=document.createElement('button');s.textContent=quiz.practice&&quiz.graded[quiz.i]?'Απάντηση υποβλήθηκε':'Υποβολή απαντήσεων';s.className='submit-answer';s.disabled=quiz.practice&&quiz.graded[quiz.i];s.onclick=submitMultiple;box.append(s)}if(quiz.practice&&quiz.graded[quiz.i])showPracticeFeedback(q);$('#prevQuestion').disabled=quiz.i===0;$('#nextQuestion').textContent=quiz.i===quiz.qs.length-1?'Ολοκλήρωση':'Επόμενη →'}
async function selectAnswer(k,b,q){if(quiz.practice&&quiz.graded[quiz.i])return;if((q.correct||[]).length>1){const a=new Set(quiz.answers[quiz.i]);a.has(k)?a.delete(k):a.add(k);quiz.answers[quiz.i]=[...a].sort();b.classList.toggle('selected');if(quiz.practice)await savePracticeProgress()}else{quiz.answers[quiz.i]=[k];if(quiz.practice){quiz.graded[quiz.i]=true;await savePracticeProgress();showQ()}else showQ()}}
async function submitMultiple(){if(!(quiz.answers[quiz.i]||[]).length)return alert('Επίλεξε τουλάχιστον μία απάντηση.');if(quiz.practice){quiz.graded[quiz.i]=true;await savePracticeProgress();showQ()}}
function isCorrect(i){const a=[...(quiz.answers[i]||[])].sort(),c=[...(quiz.qs[i].correct||[])].sort();return JSON.stringify(a)===JSON.stringify(c)}
function showPracticeFeedback(q){const chosen=quiz.answers[quiz.i]||[],correct=q.correct||[],ok=isCorrect(quiz.i);document.querySelectorAll('#quizOptions .option').forEach(b=>{const k=b.dataset.key;if(correct.includes(k))b.classList.add('correct');else if(chosen.includes(k))b.classList.add('wrong');b.disabled=true});$('#feedback').textContent=(ok?'Σωστά. ':'Λάθος. ')+(q.explanation||`Σωστή: ${correct.join(', ')}`)}
$('#prevQuestion').onclick=async()=>{if(quiz.i>0){quiz.i--;if(quiz.practice)await savePracticeProgress();showQ()}};
$('#nextQuestion').onclick=async()=>{if(quiz.practice&&!quiz.graded[quiz.i]){if(!(quiz.answers[quiz.i]||[]).length)return alert('Απάντησε πρώτα στην ερώτηση.');quiz.graded[quiz.i]=true}if(quiz.i===quiz.qs.length-1)return finishQuiz();quiz.i++;if(quiz.practice)await savePracticeProgress();showQ()};
async function finishQuiz(){const correct=quiz.qs.reduce((n,_,i)=>n+(isCorrect(i)?1:0),0),answered=quiz.answers.filter(a=>a.length).length,total=quiz.qs.length,wrong=answered-correct,unanswered=total-answered,pct=Math.round(correct*100/total);if(quiz.practice)await clearPracticeProgress();$('#resultScore').textContent=`${correct} / ${total}`;$('#resultPercent').textContent=`${pct}%`;$('#resultDetails').textContent=`Σωστές: ${correct} · Λάθος: ${wrong} · Αναπάντητες: ${unanswered}`;$('#quizView').hidden=true;$('#resultsView').hidden=false}
$('#resultsBack').onclick=()=>{$('#resultsView').hidden=true;$('#bankView').hidden=false;quiz=null};
$('#quitQuiz').onclick=async()=>{if(confirm(quiz?.practice?'Έξοδος από το Practice; Η πρόοδός σου θα αποθηκευτεί αυτόματα.':'Έξοδος από το τεστ; Η τρέχουσα προσπάθεια δεν θα αποθηκευτεί.')){if(quiz?.practice)await savePracticeProgress();quitQuiz()}};function quitQuiz(){$('#quizView').hidden=true;$('#resultsView').hidden=true;$('#bankView').hidden=false;quiz=null}
$('#exportBtn').onclick=async()=>{const blob=new Blob([JSON.stringify(await backup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mtest-local-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(f&&confirm('Θα αντικατασταθούν τα τοπικά δεδομένα. Συνέχεια;')){await restore(JSON.parse(await f.text()));renderBanks()}e.target.value=''};
function parseCSV(t){let rows=[],row=[],v='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x!==''))rows.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x!==''))rows.push(row);return rows}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
